### ISSUE TITLE
Implement bridges for the Cpp wallet library

### ISSUE THREAD

**Issue by ademcan** [cyber-republic/react-native-elastos-wallet-core#16]
We have successfully tested the bridge implementations for 3 functions (generateMnemonic, getSinglePublicKey and getSinglePrivateKey) for both iOS and Android. 
We can now continue by adding the remaining functions' bridges. 

Todo
 - [x] [Wallet balance - Android](https://github.com/cyber-republic/react-native-elastos-wallet-core/issues/6)
 - [x] [Wallet balance - iOS](https://github.com/cyber-republic/react-native-elastos-wallet-core/issues/8)
 - [x] [Wallet import/export - Android](https://github.com/cyber-republic/react-native-elastos-wallet-core/issues/5)
 - [x] [Wallet import/export - iOS](https://github.com/cyber-republic/react-native-elastos-wallet-core/issues/9)
 - [x] [Make transactions](https://github.com/cyber-republic/elastos-ReactNative-framework/issues/40)
 - [x] Transaction history

Estimated 4 hours left

**Comment by EricDualc** [comment]
yes

**Comment by EricDualc** [comment]
The bridges for android alpha was almost implemented, I think on my new commit - "add new bridges for alpha".

**Comment by andersalm** [comment]
Created new issues for remaining work 

- https://github.com/cyber-republic/react-native-elastos-wallet-core/issues/26
- https://github.com/cyber-republic/react-native-elastos-wallet-core/issues/25
- https://github.com/cyber-republic/react-native-elastos-wallet-core/issues/27
